#!/usr/bin/env python3
"""Split index.html into a Shopify section + stylesheet asset.

The homepage cannot ship as templates/index.liquid here: templates/index.json
already exists in the theme and takes precedence, and file deletion is blocked
by policy. So the page is delivered the idiomatic way instead — as one section
that the JSON template points at.

  assets/fl-home.css            the whole <style> block
  sections/cinematic-home.liquid  the <body> markup, the scripts, and the
                                  Liquid that feeds product images and prices
  templates/index.json          points at that one section

The layout supplies <html>/<head>/<body> and suppresses its own header and
footer on the index, because the page brings its own nav and footer.

Run from this directory:  python3 build-section.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'index.html')
HEAD = os.path.join(HERE, 'head.liquid')
OUT_CSS = os.path.join(HERE, 'theme', 'fl-home.css')
OUT_SEC = os.path.join(HERE, 'theme', 'cinematic-home.liquid')
OUT_TPL = os.path.join(HERE, 'theme', 'index.json')

BANNER = ('{%- comment -%}\n'
          '  Flightlab homepage. Generated by shopify/build-section.py from\n'
          '  index.html — edit that file, not this one.\n'
          '{%- endcomment -%}\n')


def main():
    html = open(SRC, encoding='utf-8').read()

    css = re.search(r'<style>(.*?)</style>', html, re.S).group(1)
    body = re.search(r'<body>(.*?)</body>', html, re.S).group(1)

    # The scripts move with the body; they only touch elements inside it.
    open(OUT_CSS, 'w', encoding='utf-8').write(css.strip() + '\n')

    liquid_head = open(HEAD, encoding='utf-8').read().strip()
    section = (BANNER + liquid_head + '\n' + body.strip() + '\n'
               '\n{% schema %}\n'
               '{\n  "name": "Forside",\n  "settings": [],\n'
               '  "presets": [{ "name": "Forside" }]\n}\n'
               '{% endschema %}\n')
    open(OUT_SEC, 'w', encoding='utf-8').write(section)

    open(OUT_TPL, 'w', encoding='utf-8').write(
        '{\n  "sections": {\n    "main": { "type": "cinematic-home", "settings": {} }\n  },\n'
        '  "order": ["main"]\n}\n')

    print('fl-home.css          %6d bytes' % os.path.getsize(OUT_CSS))
    print('cinematic-home.liquid %6d bytes' % os.path.getsize(OUT_SEC))
    print('index.json            %6d bytes' % os.path.getsize(OUT_TPL))


if __name__ == '__main__':
    main()
